 <?php
    if($this->row):
    ?>
    <div class="contentheading3"><?php echo $this->placeGreen($this->row['title']);?></div>
    <div class="small center">
        <span class="line">編輯：<?php echo $this->row['author'];?></span>
        <span class="line"><?php echo $this->row['created'];?></span>
    </div>
    <div class="contentDetail">
    	<div id="playerDiv"></div>		
		<?php if(trim($this->row['video_embed'])) :?>		
		<div class="center">			
			<?php echo $this->row['video_embed'];?>		
		</div>		
		<?php endif;?>				
		<?php if(trim($this->row['image'])):?>
		<div class="center">
			<image src="<?php echo $this->image($this->row['image'])->resize(520);?>" id="imageContent"/>		
		</div>		
		<script>
			$(document).ready(function(){		
				var width = $("img#imageContent").width();		
				if(width > 520){			
					width = 520;				
					$("img#imageContent").width(width);		
				}			
			});	
		</script>	
		<?php endif;?>
        <?php echo $this->content; ?>
    </div>
    <?php if($this->pages):?>
    <div class="pagesNav">        分頁：
        <span class="pageItemLink">
        <?php
        if($this->page < 2):
            echo "[ 1 ]";
        else:
        ?>
            [<a href="<?php echo $this->url(array('controller'=>'article','action'=>'detail','id'=>$this->row['article_id']),null,true);?>">
                1
            </a>]
        <?php
        endif;
        ?>
        </span>

        <?php
        foreach($this->pages as $p):
             if($this->page == $p['article_page']):?>
                 <span class="pageItemLink">
                     <?php echo $p['article_page'];?>
                 </span>
             <?php else:?>
                 <span class="pageItemLink">
                     [<a href="<?php echo $this->url(array('controller'=>'article','action'=>'detail','id'=>$this->row['article_id'],'page'=>$p['article_page']),null,true);?>">
                          <?php echo $p['article_page'];?>
                 </a>]
                </span>
        <?php
            endif;
        endforeach;?>
    </div>
    <?php endif;?>
    <?php
    else:
        echo "還沒有內容";
    endif;
    ?>