<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/styleadmin.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/calendar.css?random=20051112" media="screen" />

<script language="javascript" type="text/javascript" src="<?php echo $this->baseUrl();?>/js/tinymce/jscripts/tiny_mce/tiny_mce.js"></script>
<script language="javascript" type="text/javascript" src="<?php echo $this->baseUrl();?>/js/tinymce/jscripts/tiny_mce/plugins/tinybrowser/tb_tinymce.js.php"></script>
<script language="javascript" type="text/javascript">
  tinyMCE.init({
    theme : "advanced",
    mode: "textareas",
    elements : "bio", 
    language: "zh",

    theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,formatselect,fontselect,fontsizeselect",
    theme_advanced_buttons2 : "link,unlink,anchor,image,separator,"
    +"undo,redo,cleanup,code,separator,sub,sup,charmap"
    +"justifyleft,justifycenter,justifyright,justifyfull,formatselect,bullist,numlist,outdent,indent,forecolor,backcolor",
    theme_advanced_buttons3 : "",
	theme_advanced_toolbar_location : "top",
	theme_advanced_toolbar_align : "left",
	theme_advanced_statusbar_location : "bottom",
	theme_advanced_resizing : true,
	
    file_browser_callback : 'tinyBrowser'
  });

  errorId = "<?php echo $this->errorId; ?>";
</script>

