<div class="upload1">
    上傳圖片到：
    <a href="<?php echo $this->url(array('module'=>'admin','controller'=>'albumns','action'=>'detail','albumn'=>$this->albumn_id),null,true);?>">
        <?php echo $this->albumn_name;?>
    </a>
    <a class="actionBtn small" href="<?php echo $this->url(array('module'=>'admin','controller'=>'albumns','action'=>'detail','albumn'=>$this->albumn_id),null,true);?>">
        [ 返回 ]
    </a>
</div>

<?php
	if( !function_exists("imagecopyresampled") ){
		?>
	<div class="message">
		<h4><strong>Error:</strong> </h4>
		<p>Application Demo requires GD Library to be installed on your system.</p>
		<p>Usually you only have to uncomment <code>;extension=php_gd2.dll</code> by removing the semicolon <code>extension=php_gd2.dll</code> and making sure your extension_dir is pointing in the right place. <code>extension_dir = "c:\php\extensions"</code> in your php.ini file. For further reading please consult the <a href="http://ca3.php.net/manual/en/image.setup.php">PHP manual</a></p>
	</div>
<?php
	} else {
?>
建議圖片寬度為 520px
	<form>
		<div style="display: inline; border: solid 1px #7FAAFF; background-color: #C5D9FF; padding: 2px;">
			<span id="spanButtonPlaceholder"></span>
		</div>
	</form>
	
<?php
	}
?>
	<div id="divFileProgressContainer" style="height: 75px;"></div>
	<div id="thumbnails"></div>