

<div id="container">
  
    <div class="t">
        <div class="t">
            <div class="t"></div>
        </div>
    </div>
  
    <div class="m">
        
                <div id="content-form">
                    <h1 class="center">CMAT 管理入口</h1>
                    <?php if($this->notice) echo "<div class=\"notice\">$this->notice</div>";?>
                    <?php echo $this->form;?>
      
                    <div class="front_link"> <a href="<?php echo $this->baseUrl();?>/">main site</a></div>
                </div>

    </div>
    
    <div class="b">
        <div class="b">
            <div class="b"></div>
        </div>
    </div>
     
     
</div>


