<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo $this->title?$this->escape($this->title)."|":""; ?> 管理界面</title>
<link href="<?php echo $this->baseUrl();?>/css/thickbox.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl();?>/css/jquery_ui.css" rel="stylesheet" type="text/css" />
<script>
var baseUrl = '<?php echo $this->baseUrl();?>';
</script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery-1.3.2.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery-ui-1.7.1.custom.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/thickbox-compressed.js"></script>
<?php echo $this->layout()->css;?>
<?php echo $this->layout()->scripts;?>
<script>
<?php
if($this->photoId) {
     echo "var photoId = $this->photoId; 
              var photoPath = '$this->albumnPath{$this->data['albumn_id']}/';
              var curImgUrl = '{$this->data['string']}';
              ";
}
?>
</script>

<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/admin.js"></script>

</head>
<body>
<div id="cms_content">
<?php echo $this->layout()->top; ?>
<div class="left">
    <?php echo $this->layout()->controlpanel; ?>
</div>
<div class="right">
    <?php echo $this->layout()->content; ?>
</div>
<div class="clr"></div>
<?php echo $this->layout()->bottom; ?>
</div>

</body>
</html>